import Hello from '../components/Temporary/Hello.vue'
import Building from '../components/Property/Building.vue';
import AccountPeriod from '../components/New/AccountPeriod.vue';
import OpenFile from '../components/OpenFiles.vue';

export const routes = [

    //============================Temp user============================================================================================
    { name: 'Temp-Management-Type',           path: '/Temp-Management-Type',          component: Hello },
    { name: 'Temp-CompanyProfile',            path: '/Temp-CompanyProfile',           component: Hello },
    { name: 'Temp-ContactsPersons',           path: '/Temp-ContactsPersons',          component: Hello },
    { name: 'Temp-ServicePlan',               path: '/Temp-ServicePlan',              component: Hello },
    { name: 'Temp-ServiceContract',           path: '/Temp-ServiceContract',          component: Hello },
    { name: 'Temp-TermsOfAgreement',          path: '/Temp-TermsOfAgreement',         component: Hello },
    { name: 'Temp-DocumentsSubmission',       path: '/Temp-DocumentsSubmission',      component: Hello },
    { name: 'Temp-ActivationStatus',          path: '/Temp-ActivationStatus',         component: Hello },

    // ============================New=============================================================================
    { name: 'Company-Profile',                path: '/Company-Profile',               component: Hello },
    { name: 'Customer-Property',              path: '/Customer-Property',             component: Hello },
    { name: 'Application-Form',               path: '/Application-Form',              component: Hello },
    { name: 'Customer-Seller',                path: '/Customer-Seller',               component: Hello },
    { name: 'Customer-Service',               path: '/Customer-Service',              component: Hello },
    { name: 'Rule-Policy',                    path: '/Rule-Policy',                   component: Hello },
    { name: 'Procudure-Instruction',          path: '/Procudure-Instruction',         component: Hello },
    { name: 'Account-Holder',                 path: '/Account-Holder',               component: Hello },
    { name: 'Coa-Setting',                    path: '/Coa-Setting',                  component: Hello },
    { name: 'Chart-Accounts',                 path: '/Chart-Accounts',               component: Hello },
    { name: 'Taxes',                          path: '/Taxes',                        component: Hello },
    { name: 'Service-Item',                   path: '/Service-Item',                 component: Hello },
    { name: 'Inventory-Item',                 path: '/Inventory-Item',               component: Hello },
    { name: 'Fixed-Asset',                    path: '/Fixed-Asset',                  component: Hello },
    { name: 'Project',                        path: '/Project',                      component: Hello },
    { name: 'Utilities',                      path: '/Utilities',                    component: Hello },

    //================================Property===========================================================================================================
    { name: 'Building',                       path: '/Building',                      component: Building },
    { name: 'Floors',                         path: '/Floors',                        component: Hello },
    { name: 'ResidentalSuites',               path: '/ResidentalSuites',              component: Hello },
    { name: 'CommercialUnit',                 path: '/CommercialUnit',                component: Hello },
    { name: 'CommonArea',                     path: '/CommonArea',                    component: Hello },
    { name: 'SupportingRoom',                 path: '/SupportingRoom',                component: Hello },
    { name: 'ParkingLot',                     path: '/ParkingLot',                    component: Hello },
    { name: 'Bike-Lot',                       path: '/Bike-Lot',                      component: Hello },
    { name: 'Storage-Lot',                    path: '/Storage-Lot',                   component: Hello },
    { name: 'Mail-Room',                      path: '/Mail-Room',                     component: Hello },
    { name: 'Property-Attrebution',           path: '/Property-Attrebution',          component: Hello },
    { name: 'NewPostingJobs',                 path: '/NewPostingJobs',                component: Hello },
    { name: 'PostingHousingRental',           path: '/PostingHousingRental',          component: Hello },
    { name: 'Modules',                        path: '/Modules',                       component: Hello },
    { name: 'Menus',                          path: '/Menus',                         component: Hello },
    { name: 'Open-File',                      path: '/Open-File',                     component: OpenFile },

    //=======================================Transaction=================================================================================
    { name: 'Purchase',                       path: '/Purchase',                      component: Hello },
    { name: 'Sales',                          path: '/Sales',                         component: Hello },
    { name: 'Forms',                          path: '/Forms',                         component: Hello },

    //============================Account Holder=========================================
    { name: 'Bank',                           path: '/Bank',                          component: Hello },
    { name: 'BoardofDirector',                path: '/BoardofDirector',               component: Hello },
    { name: 'Client',                         path: '/Client',                        component: Hello },
    { name: 'CreditCardCompany',              path: '/CreditCardCompany',             component: Hello },
    { name: 'Customer',                       path: '/Customer',                      component: Hello },
    { name: 'Donor',                          path: '/Donor',                         component: Hello },
    { name: 'Employee',                       path: '/Employee',                      component: Hello },
    { name: 'Government',                     path: '/Government',                    component: Hello },
    { name: 'Investor',                       path: '/Investor',                      component: Hello },
    { name: 'Landlord',                       path: '/Landlord',                      component: Hello },
    { name: 'Leaseholder',                    path: '/Leaseholder',                   component: Hello },
    { name: 'PrivateLoanLender',              path: '/PrivateLoanLender',             component: Hello },
    { name: 'ServiceProvider',                path: '/ServiceProvider',               component: Hello},
    { name: 'Shareholder',                    path: '/Shareholder',                   component: Hello },
    { name: 'Student',                        path: '/Student',                       component: Hello },
    { name: 'Seller',                         path: '/Seller',                        component: Hello },
    { name: 'Tenant',                         path: '/Tenant',                        component: Hello },
    { name: 'Visitor',                        path: '/Visitor',                       component: Hello },
    { name: 'Volunteer',                      path: '/Volunteer',                     component: Hello },
    //===========================Account Holder finish================================================

    { name: 'Users',                          path: '/Users',                         component: Hello },
    { name: 'User-Privilige',                 path: '/User-Privilige',                component: Hello },
    { name: 'User-Info',                      path: '/User-Info',                     component: Hello },
    { name: 'Company-Info',                   path: '/Company-Info',                  component: Hello },
    { name: 'Countries',                      path: '/Countries',                     component: Hello },
    { name: 'Proviences',                     path: '/Proviences',                    component: Hello },
    { name: 'ServicePlans',                   path: '/ServicePlans',                  component: Hello },
    { name: 'Account-Floor',                  path: '/Account-Floor',                 component: Hello },
    { name: 'Account-Suites',                 path: '/Account-Suites',                component: Hello },
    { name: 'Account-Maintenance-Room',       path: '/Account-Maintenance-Room',      component: Hello },
    { name: 'Account-Parking',                path: '/Account-Parking',               component: Hello },
    { name: 'Account-Lockers',                path: '/Account-Lockers',               component: Hello },
    { name: 'FireExtinguisher-Locations',     path: '/FireExtinguisher-Locations',    component: Hello },
    { name: 'TowerInspection-Checklist',      path: '/TowerInspection-Checklist',     component: Hello },
    { name: 'Account-Sprinkler',              path: '/Account-Sprinkler',             component: Hello },
    { name: 'Account-Breakers',               path: '/Account-Breakers',              component: Hello },
    { name: 'Account-EmergencyExits',         path: '/Account-EmergencyExits',        component: Hello },
    { name: 'EmergencyWater-ShutDown',        path: '/EmergencyWater-ShutDown',       component: Hello },
    { name: 'Account-ServicesContractors',    path: '/Account-ServicesContractors',   component: Hello },
    { name: 'Account-FirePanel',              path: '/Account-FirePanel',             component: Hello },
    { name: 'Account-GymEquipments',          path: '/Account-GymEquipments',         component: Hello },
    { name: 'Account-SwimmingPool ',          path: '/Account-SwimmingPool ',         component: Hello },
    { name: 'Account-Compactor ',             path: '/Account-Compactor ',            component: Hello },
    { name: 'Account-Elevator',               path: '/Account-Elevator',              component: Hello },
    { name: 'Account-AED',                    path: '/Account-AED',                   component: Hello },
    { name: 'Account-SecurityCamera ',        path: '/Account-SecurityCamera ',       component: Hello },
    { name: 'Account-FOB',                    path: '/Account-FOB',                   component: Hello },
    { name: 'Account-ScheduledInspection',    path: '/Account-ScheduledInspection',   component: Hello },
    { name: 'Account-ScheduledServices',      path: '/Account-ScheduledServices',     component: Hello },
    { name: 'Account-SafeBox',                path: '/Account-SafeBox',               component: Hello },
    { name: 'Account-PhoneCable',             path: '/Account-PhoneCable',            component: Hello },
    { name: 'General-Info',                   path: '/General-Info',                  component: Hello },
    { name: 'Account-period',                 path: '/Account-period',                component: AccountPeriod }
];